// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup
{
    /// <summary>
    /// Builds and executes requests for operations under \redis\disable-dailybackup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DisableDailybackupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Upstash.OpenApiClient.redis.disableDailybackup.item collection</summary>
        /// <param name="position">The ID of the Redis database</param>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.Item.DisableDailybackupItemRequestBuilder"/></returns>
        public global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.Item.DisableDailybackupItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.Item.DisableDailybackupItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.DisableDailybackupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisableDailybackupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/redis/disable-dailybackup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.DisableDailybackupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisableDailybackupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/redis/disable-dailybackup", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
