// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Upstash.OpenApiClient.Auditlogs;
using Soenneker.Upstash.OpenApiClient.Qstash;
using Soenneker.Upstash.OpenApiClient.Redis;
using Soenneker.Upstash.OpenApiClient.Search;
using Soenneker.Upstash.OpenApiClient.Team;
using Soenneker.Upstash.OpenApiClient.Teams;
using Soenneker.Upstash.OpenApiClient.Vector;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Upstash.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpstashOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The auditlogs property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Auditlogs.AuditlogsRequestBuilder Auditlogs
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Auditlogs.AuditlogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The qstash property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.QstashRequestBuilder Qstash
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.QstashRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The redis property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.RedisRequestBuilder Redis
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.RedisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Team.TeamRequestBuilder Team
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Team.TeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vector property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Vector.VectorRequestBuilder Vector
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Vector.VectorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.UpstashOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpstashOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.upstash.com/v2";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
