// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Upstash.OpenApiClient.Qstash.DisableProdpack;
using Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack;
using Soenneker.Upstash.OpenApiClient.Qstash.Ipv4;
using Soenneker.Upstash.OpenApiClient.Qstash.MoveToTeam;
using Soenneker.Upstash.OpenApiClient.Qstash.RotateToken;
using Soenneker.Upstash.OpenApiClient.Qstash.SetPlan;
using Soenneker.Upstash.OpenApiClient.Qstash.Stats;
using Soenneker.Upstash.OpenApiClient.Qstash.UpdateBudget;
using Soenneker.Upstash.OpenApiClient.Qstash.User;
using Soenneker.Upstash.OpenApiClient.Qstash.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Upstash.OpenApiClient.Qstash
{
    /// <summary>
    /// Builds and executes requests for operations under \qstash
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QstashRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The disableProdpack property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.DisableProdpack.DisableProdpackRequestBuilder DisableProdpack
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.DisableProdpack.DisableProdpackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enableProdpack property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.EnableProdpackRequestBuilder EnableProdpack
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.EnableProdpackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ipv4 property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.Ipv4.Ipv4RequestBuilder Ipv4
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.Ipv4.Ipv4RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The moveToTeam property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.MoveToTeam.MoveToTeamRequestBuilder MoveToTeam
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.MoveToTeam.MoveToTeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rotateToken property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.RotateToken.RotateTokenRequestBuilder RotateToken
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.RotateToken.RotateTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setPlan property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.SetPlan.SetPlanRequestBuilder SetPlan
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.SetPlan.SetPlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.Stats.StatsRequestBuilder Stats
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateBudget property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.UpdateBudget.UpdateBudgetRequestBuilder UpdateBudget
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.UpdateBudget.UpdateBudgetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Qstash.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Qstash.QstashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QstashRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qstash", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Qstash.QstashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QstashRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qstash", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
