// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack
{
    /// <summary>
    /// Builds and executes requests for operations under \qstash\enable-prodpack
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnableProdpackRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Upstash.OpenApiClient.qstash.enableProdpack.item collection</summary>
        /// <param name="position">QStash user ID</param>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.Item.EnableProdpackItemRequestBuilder"/></returns>
        public global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.Item.EnableProdpackItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.Item.EnableProdpackItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.EnableProdpackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnableProdpackRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qstash/enable-prodpack", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Qstash.EnableProdpack.EnableProdpackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnableProdpackRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qstash/enable-prodpack", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
