// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget
{
    /// <summary>
    /// Builds and executes requests for operations under \redis\update-budget
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateBudgetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Upstash.OpenApiClient.redis.updateBudget.item collection</summary>
        /// <param name="position">The ID of the database whose budget will be updated</param>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.Item.UpdateBudgetItemRequestBuilder"/></returns>
        public global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.Item.UpdateBudgetItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.Item.UpdateBudgetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.UpdateBudgetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateBudgetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/redis/update-budget", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.UpdateBudgetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateBudgetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/redis/update-budget", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
