// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuditLog : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Numeric ID representing the specific action type</summary>
        public int? Action { get; set; }
        /// <summary>Human-readable description of the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionString { get; set; }
#nullable restore
#else
        public string ActionString { get; set; }
#endif
        /// <summary>The user or system that performed the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Actor { get; set; }
#nullable restore
#else
        public string Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID or email of the customer associated with the log</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>The primary entity affected by the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Entity { get; set; }
#nullable restore
#else
        public string Entity { get; set; }
#endif
        /// <summary>The IP address from which the request originated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ip { get; set; }
#nullable restore
#else
        public string Ip { get; set; }
#endif
        /// <summary>Unique identifier for the log entry</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogId { get; set; }
#nullable restore
#else
        public string LogId { get; set; }
#endif
        /// <summary>Additional notes regarding the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>formatted string for display purposes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReadableFormat { get; set; }
#nullable restore
#else
        public string ReadableFormat { get; set; }
#endif
        /// <summary>The reason for the action, if provided</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>A secondary entity affected, &quot;&quot; or &quot;NA&quot; if not applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryEntity { get; set; }
#nullable restore
#else
        public string SecondaryEntity { get; set; }
#endif
        /// <summary>The source method or client used to perform the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>A tertiary entity affected, &quot;&quot; or &quot;NA&quot; if not applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThirdEntity { get; set; }
#nullable restore
#else
        public string ThirdEntity { get; set; }
#endif
        /// <summary>Unix timestamp of when the action occurred</summary>
        public long? Timestamp { get; set; }
        /// <summary>Time to live (expiration) timestamp for this log entry</summary>
        public long? Ttl { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.AuditLog"/> and sets the default values.
        /// </summary>
        public AuditLog()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.AuditLog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.AuditLog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.AuditLog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetIntValue(); } },
                { "action_string", n => { ActionString = n.GetStringValue(); } },
                { "actor", n => { Actor = n.GetStringValue(); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "entity", n => { Entity = n.GetStringValue(); } },
                { "ip", n => { Ip = n.GetStringValue(); } },
                { "log_id", n => { LogId = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "readable_format", n => { ReadableFormat = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "secondary_entity", n => { SecondaryEntity = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "third_entity", n => { ThirdEntity = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetLongValue(); } },
                { "ttl", n => { Ttl = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("action", Action);
            writer.WriteStringValue("action_string", ActionString);
            writer.WriteStringValue("actor", Actor);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteStringValue("entity", Entity);
            writer.WriteStringValue("ip", Ip);
            writer.WriteStringValue("log_id", LogId);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("readable_format", ReadableFormat);
            writer.WriteStringValue("reason", Reason);
            writer.WriteStringValue("secondary_entity", SecondaryEntity);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("third_entity", ThirdEntity);
            writer.WriteLongValue("timestamp", Timestamp);
            writer.WriteLongValue("ttl", Ttl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
