// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Backup : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the backup</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackupId { get; set; }
#nullable restore
#else
        public string BackupId { get; set; }
#endif
        /// <summary>Size of the backup</summary>
        public long? BackupSize { get; set; }
        /// <summary>Creation time of the backup as Unix time</summary>
        public long? CreationTime { get; set; }
        /// <summary>Customer ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Daily backup status</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.BackupDailyBackup? DailyBackup { get; set; }
        /// <summary>ID of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseId { get; set; }
#nullable restore
#else
        public string DatabaseId { get; set; }
#endif
        /// <summary>Hourly backup status</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.BackupHourlyBackup? HourlyBackup { get; set; }
        /// <summary>Internal backup tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalBackupTag { get; set; }
#nullable restore
#else
        public string InternalBackupTag { get; set; }
#endif
        /// <summary>Name of the backup</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>State of the backup</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.BackupState? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.Backup"/> and sets the default values.
        /// </summary>
        public Backup()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.Backup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.Backup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.Backup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backup_id", n => { BackupId = n.GetStringValue(); } },
                { "backup_size", n => { BackupSize = n.GetLongValue(); } },
                { "creation_time", n => { CreationTime = n.GetLongValue(); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "daily_backup", n => { DailyBackup = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.BackupDailyBackup>(); } },
                { "database_id", n => { DatabaseId = n.GetStringValue(); } },
                { "hourly_backup", n => { HourlyBackup = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.BackupHourlyBackup>(); } },
                { "internal_backup_tag", n => { InternalBackupTag = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.BackupState>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("backup_id", BackupId);
            writer.WriteLongValue("backup_size", BackupSize);
            writer.WriteLongValue("creation_time", CreationTime);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.BackupDailyBackup>("daily_backup", DailyBackup);
            writer.WriteStringValue("database_id", DatabaseId);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.BackupHourlyBackup>("hourly_backup", HourlyBackup);
            writer.WriteStringValue("internal_backup_tag", InternalBackupTag);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.BackupState>("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
