// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChangePlanRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to enable automatic upgrade for the database</summary>
        public bool? AutoUpgrade { get; set; }
        /// <summary>ID of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseId { get; set; }
#nullable restore
#else
        public string DatabaseId { get; set; }
#endif
        /// <summary>The new plan for the database</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequestPlanName? PlanName { get; set; }
        /// <summary>Whether to enable the production pack for the database</summary>
        public bool? ProdPackEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequest"/> and sets the default values.
        /// </summary>
        public ChangePlanRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_upgrade", n => { AutoUpgrade = n.GetBoolValue(); } },
                { "database_id", n => { DatabaseId = n.GetStringValue(); } },
                { "plan_name", n => { PlanName = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequestPlanName>(); } },
                { "prod_pack_enabled", n => { ProdPackEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_upgrade", AutoUpgrade);
            writer.WriteStringValue("database_id", DatabaseId);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.ChangePlanRequestPlanName>("plan_name", PlanName);
            writer.WriteBoolValue("prod_pack_enabled", ProdPackEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
