// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The new plan for the database</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChangePlanRequestPlanName
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "payg")]
        #pragma warning disable CS1591
        Payg,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_250mb")]
        #pragma warning disable CS1591
        Fixed250Mb,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_1gb")]
        #pragma warning disable CS1591
        Fixed1Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_5gb")]
        #pragma warning disable CS1591
        Fixed5Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_10gb")]
        #pragma warning disable CS1591
        Fixed10Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_50gb")]
        #pragma warning disable CS1591
        Fixed50Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_100gb")]
        #pragma warning disable CS1591
        Fixed100Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_500gb")]
        #pragma warning disable CS1591
        Fixed500Gb,
        #pragma warning restore CS1591
    }
}
