// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateDatabaseRequestReadRegionsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "us-east-1")]
        #pragma warning disable CS1591
        UsEast1,
        #pragma warning restore CS1591
        [EnumMember(Value = "us-east-2")]
        #pragma warning disable CS1591
        UsEast2,
        #pragma warning restore CS1591
        [EnumMember(Value = "us-west-1")]
        #pragma warning disable CS1591
        UsWest1,
        #pragma warning restore CS1591
        [EnumMember(Value = "us-west-2")]
        #pragma warning disable CS1591
        UsWest2,
        #pragma warning restore CS1591
        [EnumMember(Value = "ca-central-1")]
        #pragma warning disable CS1591
        CaCentral1,
        #pragma warning restore CS1591
        [EnumMember(Value = "eu-central-1")]
        #pragma warning disable CS1591
        EuCentral1,
        #pragma warning restore CS1591
        [EnumMember(Value = "eu-west-1")]
        #pragma warning disable CS1591
        EuWest1,
        #pragma warning restore CS1591
        [EnumMember(Value = "eu-west-2")]
        #pragma warning disable CS1591
        EuWest2,
        #pragma warning restore CS1591
        [EnumMember(Value = "sa-east-1")]
        #pragma warning disable CS1591
        SaEast1,
        #pragma warning restore CS1591
        [EnumMember(Value = "ap-south-1")]
        #pragma warning disable CS1591
        ApSouth1,
        #pragma warning restore CS1591
        [EnumMember(Value = "ap-northeast-1")]
        #pragma warning disable CS1591
        ApNortheast1,
        #pragma warning restore CS1591
        [EnumMember(Value = "ap-southeast-1")]
        #pragma warning disable CS1591
        ApSoutheast1,
        #pragma warning restore CS1591
        [EnumMember(Value = "ap-southeast-2")]
        #pragma warning disable CS1591
        ApSoutheast2,
        #pragma warning restore CS1591
    }
}
