// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateDatabaseRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Monthly budget of the database</summary>
        public int? Budget { get; set; }
        /// <summary>Name of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseName { get; set; }
#nullable restore
#else
        public string DatabaseName { get; set; }
#endif
        /// <summary>Whether to enable eviction for the database</summary>
        public bool? Eviction { get; set; }
        /// <summary>Specifies the fixed plan type for the database.If omitted, the database defaults to either the pay-as-you-go or free plan, based on the account type.</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPlan? Plan { get; set; }
        /// <summary>Desired cloud platform for the database.</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPlatform? Platform { get; set; }
        /// <summary>Primary Region of the Global Database</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPrimaryRegion? PrimaryRegion { get; set; }
        /// <summary>Array of Read Regions of the Database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestReadRegionsItem?>? ReadRegions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestReadRegionsItem?> ReadRegions { get; set; }
#endif
        /// <summary>Whether to enable TLS for the database</summary>
        public bool? Tls { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequest"/> and sets the default values.
        /// </summary>
        public CreateDatabaseRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "budget", n => { Budget = n.GetIntValue(); } },
                { "database_name", n => { DatabaseName = n.GetStringValue(); } },
                { "eviction", n => { Eviction = n.GetBoolValue(); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPlan>(); } },
                { "platform", n => { Platform = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPlatform>(); } },
                { "primary_region", n => { PrimaryRegion = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPrimaryRegion>(); } },
                { "read_regions", n => { ReadRegions = n.GetCollectionOfEnumValues<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestReadRegionsItem>()?.AsList(); } },
                { "tls", n => { Tls = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("budget", Budget);
            writer.WriteStringValue("database_name", DatabaseName);
            writer.WriteBoolValue("eviction", Eviction);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPlan>("plan", Plan);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPlatform>("platform", Platform);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestPrimaryRegion>("primary_region", PrimaryRegion);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Upstash.OpenApiClient.Models.CreateDatabaseRequestReadRegionsItem>("read_regions", ReadRegions);
            writer.WriteBoolValue("tls", Tls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
