// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateIndexRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of values in a single vector</summary>
        public double? DimensionCount { get; set; }
        /// <summary>The embedding model to use for the index</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestEmbeddingModel? EmbeddingModel { get; set; }
        /// <summary>The type of the vector index</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestIndexType? IndexType { get; set; }
        /// <summary>Name of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Region of the database</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestRegion? Region { get; set; }
        /// <summary>Similarity function that&apos;s used to calculate the distance between two vectors</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestSimilarityFunction? SimilarityFunction { get; set; }
        /// <summary>The sparse embedding model to be used for indexes</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestSparseEmbeddingModel? SparseEmbeddingModel { get; set; }
        /// <summary>The payment plan of your index</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest"/> and sets the default values.
        /// </summary>
        public CreateIndexRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dimension_count", n => { DimensionCount = n.GetDoubleValue(); } },
                { "embedding_model", n => { EmbeddingModel = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestEmbeddingModel>(); } },
                { "index_type", n => { IndexType = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestIndexType>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestRegion>(); } },
                { "similarity_function", n => { SimilarityFunction = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestSimilarityFunction>(); } },
                { "sparse_embedding_model", n => { SparseEmbeddingModel = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestSparseEmbeddingModel>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("dimension_count", DimensionCount);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestEmbeddingModel>("embedding_model", EmbeddingModel);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestIndexType>("index_type", IndexType);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestRegion>("region", Region);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestSimilarityFunction>("similarity_function", SimilarityFunction);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestSparseEmbeddingModel>("sparse_embedding_model", SparseEmbeddingModel);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequestType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
