// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Desired cloud platform for the database.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateDatabaseRequestPlatform
    {
        [EnumMember(Value = "aws")]
        #pragma warning disable CS1591
        Aws,
        #pragma warning restore CS1591
        [EnumMember(Value = "gcp")]
        #pragma warning disable CS1591
        Gcp,
        #pragma warning restore CS1591
    }
}
