// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The type of the vector index</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateIndexRequestIndexType
    {
        [EnumMember(Value = "DENSE")]
        #pragma warning disable CS1591
        Dense,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPARSE")]
        #pragma warning disable CS1591
        Sparse,
        #pragma warning restore CS1591
        [EnumMember(Value = "HYBRID")]
        #pragma warning disable CS1591
        Hybrid,
        #pragma warning restore CS1591
    }
}
