// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Payment plan of the database</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseType
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "payg")]
        #pragma warning disable CS1591
        Payg,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro")]
        #pragma warning disable CS1591
        Pro,
        #pragma warning restore CS1591
        [EnumMember(Value = "paid")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
    }
}
