// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Database : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of all regions in the database cluster</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllMembers { get; set; }
#nullable restore
#else
        public List<string> AllMembers { get; set; }
#endif
        /// <summary>Automatic upgrade capability is enabled</summary>
        public bool? AutoUpgrade { get; set; }
        /// <summary>Allocated monthly budget for the database</summary>
        public long? Budget { get; set; }
        /// <summary>Strong consistency mode is enabled</summary>
        public bool? Consistent { get; set; }
        /// <summary>Creation time of the database as Unix time</summary>
        public long? CreationTime { get; set; }
        /// <summary>Owner identifier of the database (may be email or marketplace-scoped email)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Whether daily backup is enabled</summary>
        public bool? DailyBackupEnabled { get; set; }
        /// <summary>ID of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseId { get; set; }
#nullable restore
#else
        public string DatabaseId { get; set; }
#endif
        /// <summary>Name of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseName { get; set; }
#nullable restore
#else
        public string DatabaseName { get; set; }
#endif
        /// <summary>Default user access status in ACL</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbAclDefaultUserStatus? DbAclDefaultUserStatus { get; set; }
        /// <summary>Access Control List enabled status</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbAclEnabled? DbAclEnabled { get; set; }
        /// <summary>Connection idle timeout in nanoseconds</summary>
        public long? DbConnIdleTimeout { get; set; }
        /// <summary>Total disk size limit that can be used for the database currently(in bytes)</summary>
        public long? DbDiskThreshold { get; set; }
        /// <summary>Database-level eviction policy status</summary>
        public bool? DbEviction { get; set; }
        /// <summary>Lua script execution credits per minute</summary>
        public long? DbLuaCreditsPerMin { get; set; }
        /// <summary>Lua script execution timeout in nanoseconds</summary>
        public long? DbLuaTimeout { get; set; }
        /// <summary>Max number of concurrent clients can be opened on this database currently</summary>
        public long? DbMaxClients { get; set; }
        /// <summary>Max number of commands can be sent to the database per second</summary>
        public long? DbMaxCommandsPerSecond { get; set; }
        /// <summary>Max size of an entry that will be accepted by the database currently(in bytes)</summary>
        public long? DbMaxEntrySize { get; set; }
        /// <summary>Maximum load operations per second</summary>
        public long? DbMaxLoadsPerSec { get; set; }
        /// <summary>Max size of a request that will be accepted by the database currently(in bytes)</summary>
        public long? DbMaxRequestSize { get; set; }
        /// <summary>Max size of a memory the database can use(in bytes)</summary>
        public long? DbMemoryThreshold { get; set; }
        /// <summary>Total number of commands can be sent to the database</summary>
        public long? DbRequestLimit { get; set; }
        /// <summary>Resource allocation tier</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbResourceSize? DbResourceSize { get; set; }
        /// <summary>Store connection idle timeout in nanoseconds</summary>
        public long? DbStoreMaxIdle { get; set; }
        /// <summary>Database storage engine type</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbType? DbType { get; set; }
        /// <summary>Endpoint identifier or hostname of the database (may be a slug like &quot;beloved-stallion-58500&quot; or a full host)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>Entry eviction is enabled</summary>
        public bool? Eviction { get; set; }
        /// <summary>Unix timestamp of the last plan upgrade</summary>
        public long? LastPlanUpgradeTime { get; set; }
        /// <summary>Current modifying state of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModifyingState { get; set; }
#nullable restore
#else
        public string ModifyingState { get; set; }
#endif
        /// <summary>Database port for clients to connect</summary>
        public long? Port { get; set; }
        /// <summary>List of primary regions in the database cluster</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PrimaryMembers { get; set; }
#nullable restore
#else
        public List<string> PrimaryMembers { get; set; }
#endif
        /// <summary>Primary region of the database cluster</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabasePrimaryRegion? PrimaryRegion { get; set; }
        /// <summary>Production pack enabled status</summary>
        public bool? ProdPackEnabled { get; set; }
        /// <summary>Prometheus integration enabled status</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabasePrometheusEnabled? PrometheusEnabled { get; set; }
        /// <summary>Array of read regions of the database</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReadRegions { get; set; }
#nullable restore
#else
        public List<string> ReadRegions { get; set; }
#endif
        /// <summary>The region where database is hosted</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.GlobalRegion? Region { get; set; }
        /// <summary>Replica factor of the database</summary>
        public int? Replicas { get; set; }
        /// <summary>Security add-ons and their enablement status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons? SecurityAddons { get; set; }
#nullable restore
#else
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons SecurityAddons { get; set; }
#endif
        /// <summary>State of database</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseState? State { get; set; }
        /// <summary>TLS/SSL is enabled or not</summary>
        public bool? Tls { get; set; }
        /// <summary>Payment plan of the database</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.DatabaseType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.Database"/> and sets the default values.
        /// </summary>
        public Database()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.Database"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.Database CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.Database();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "all_members", n => { AllMembers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "auto_upgrade", n => { AutoUpgrade = n.GetBoolValue(); } },
                { "budget", n => { Budget = n.GetLongValue(); } },
                { "consistent", n => { Consistent = n.GetBoolValue(); } },
                { "creation_time", n => { CreationTime = n.GetLongValue(); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "daily_backup_enabled", n => { DailyBackupEnabled = n.GetBoolValue(); } },
                { "database_id", n => { DatabaseId = n.GetStringValue(); } },
                { "database_name", n => { DatabaseName = n.GetStringValue(); } },
                { "db_acl_default_user_status", n => { DbAclDefaultUserStatus = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbAclDefaultUserStatus>(); } },
                { "db_acl_enabled", n => { DbAclEnabled = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbAclEnabled>(); } },
                { "db_conn_idle_timeout", n => { DbConnIdleTimeout = n.GetLongValue(); } },
                { "db_disk_threshold", n => { DbDiskThreshold = n.GetLongValue(); } },
                { "db_eviction", n => { DbEviction = n.GetBoolValue(); } },
                { "db_lua_credits_per_min", n => { DbLuaCreditsPerMin = n.GetLongValue(); } },
                { "db_lua_timeout", n => { DbLuaTimeout = n.GetLongValue(); } },
                { "db_max_clients", n => { DbMaxClients = n.GetLongValue(); } },
                { "db_max_commands_per_second", n => { DbMaxCommandsPerSecond = n.GetLongValue(); } },
                { "db_max_entry_size", n => { DbMaxEntrySize = n.GetLongValue(); } },
                { "db_max_loads_per_sec", n => { DbMaxLoadsPerSec = n.GetLongValue(); } },
                { "db_max_request_size", n => { DbMaxRequestSize = n.GetLongValue(); } },
                { "db_memory_threshold", n => { DbMemoryThreshold = n.GetLongValue(); } },
                { "db_request_limit", n => { DbRequestLimit = n.GetLongValue(); } },
                { "db_resource_size", n => { DbResourceSize = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbResourceSize>(); } },
                { "db_store_max_idle", n => { DbStoreMaxIdle = n.GetLongValue(); } },
                { "db_type", n => { DbType = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbType>(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "eviction", n => { Eviction = n.GetBoolValue(); } },
                { "last_plan_upgrade_time", n => { LastPlanUpgradeTime = n.GetLongValue(); } },
                { "modifying_state", n => { ModifyingState = n.GetStringValue(); } },
                { "port", n => { Port = n.GetLongValue(); } },
                { "primary_members", n => { PrimaryMembers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "primary_region", n => { PrimaryRegion = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabasePrimaryRegion>(); } },
                { "prod_pack_enabled", n => { ProdPackEnabled = n.GetBoolValue(); } },
                { "prometheus_enabled", n => { PrometheusEnabled = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabasePrometheusEnabled>(); } },
                { "read_regions", n => { ReadRegions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.GlobalRegion>(); } },
                { "replicas", n => { Replicas = n.GetIntValue(); } },
                { "securityAddons", n => { SecurityAddons = n.GetObjectValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons>(global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseState>(); } },
                { "tls", n => { Tls = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("all_members", AllMembers);
            writer.WriteBoolValue("auto_upgrade", AutoUpgrade);
            writer.WriteLongValue("budget", Budget);
            writer.WriteBoolValue("consistent", Consistent);
            writer.WriteLongValue("creation_time", CreationTime);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteBoolValue("daily_backup_enabled", DailyBackupEnabled);
            writer.WriteStringValue("database_id", DatabaseId);
            writer.WriteStringValue("database_name", DatabaseName);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbAclDefaultUserStatus>("db_acl_default_user_status", DbAclDefaultUserStatus);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbAclEnabled>("db_acl_enabled", DbAclEnabled);
            writer.WriteLongValue("db_conn_idle_timeout", DbConnIdleTimeout);
            writer.WriteLongValue("db_disk_threshold", DbDiskThreshold);
            writer.WriteBoolValue("db_eviction", DbEviction);
            writer.WriteLongValue("db_lua_credits_per_min", DbLuaCreditsPerMin);
            writer.WriteLongValue("db_lua_timeout", DbLuaTimeout);
            writer.WriteLongValue("db_max_clients", DbMaxClients);
            writer.WriteLongValue("db_max_commands_per_second", DbMaxCommandsPerSecond);
            writer.WriteLongValue("db_max_entry_size", DbMaxEntrySize);
            writer.WriteLongValue("db_max_loads_per_sec", DbMaxLoadsPerSec);
            writer.WriteLongValue("db_max_request_size", DbMaxRequestSize);
            writer.WriteLongValue("db_memory_threshold", DbMemoryThreshold);
            writer.WriteLongValue("db_request_limit", DbRequestLimit);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbResourceSize>("db_resource_size", DbResourceSize);
            writer.WriteLongValue("db_store_max_idle", DbStoreMaxIdle);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseDbType>("db_type", DbType);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteBoolValue("eviction", Eviction);
            writer.WriteLongValue("last_plan_upgrade_time", LastPlanUpgradeTime);
            writer.WriteStringValue("modifying_state", ModifyingState);
            writer.WriteLongValue("port", Port);
            writer.WriteCollectionOfPrimitiveValues<string>("primary_members", PrimaryMembers);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabasePrimaryRegion>("primary_region", PrimaryRegion);
            writer.WriteBoolValue("prod_pack_enabled", ProdPackEnabled);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabasePrometheusEnabled>("prometheus_enabled", PrometheusEnabled);
            writer.WriteCollectionOfPrimitiveValues<string>("read_regions", ReadRegions);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.GlobalRegion>("region", Region);
            writer.WriteIntValue("replicas", Replicas);
            writer.WriteObjectValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons>("securityAddons", SecurityAddons);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseState>("state", State);
            writer.WriteBoolValue("tls", Tls);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.DatabaseType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
