// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Database storage engine type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseDbType
    {
        [EnumMember(Value = "bolt")]
        #pragma warning disable CS1591
        Bolt,
        #pragma warning restore CS1591
        [EnumMember(Value = "badger")]
        #pragma warning disable CS1591
        Badger,
        #pragma warning restore CS1591
        [EnumMember(Value = "pebble")]
        #pragma warning disable CS1591
        Pebble,
        #pragma warning restore CS1591
    }
}
