// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>State of database</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseState
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "passive")]
        #pragma warning disable CS1591
        Passive,
        #pragma warning restore CS1591
    }
}
