// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DatabaseStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Bandwidth usage over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Bandwidths { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Bandwidths { get; set; }
#endif
        /// <summary>Command-specific counts over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.CommandCount>? CommandCounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.CommandCount> CommandCounts { get; set; }
#endif
        /// <summary>Connection count over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? ConnectionCount { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> ConnectionCount { get; set; }
#endif
        /// <summary>Current storage used (bytes)</summary>
        public int? CurrentStorage { get; set; }
        /// <summary>Total daily bandwidth usage in bytes</summary>
        public long? Dailybandwidth { get; set; }
        /// <summary>Daily billing amounts over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Dailybilling { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Dailybilling { get; set; }
#endif
        /// <summary>Total number of commands executed today</summary>
        public int? DailyNetCommands { get; set; }
        /// <summary>Total number of read requests executed today</summary>
        public int? DailyReadRequests { get; set; }
        /// <summary>Daily requests over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Dailyrequests { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Dailyrequests { get; set; }
#endif
        /// <summary>Total number of write requests executed today</summary>
        public int? DailyWriteRequests { get; set; }
        /// <summary>Days of the week for measurement</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Days { get; set; }
#nullable restore
#else
        public List<string> Days { get; set; }
#endif
        /// <summary>Disk usage over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Diskusage { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Diskusage { get; set; }
#endif
        /// <summary>Cache hits over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Hits { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Hits { get; set; }
#endif
        /// <summary>Total number of keys in the database over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Keyspace { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Keyspace { get; set; }
#endif
        /// <summary>99th percentile latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Latency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Latency99 { get; set; }
#endif
        /// <summary>Average latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Latencymean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Latencymean { get; set; }
#endif
        /// <summary>Cache misses over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Misses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Misses { get; set; }
#endif
        /// <summary>The monitor_count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData? MonitorCount { get; set; }
#nullable restore
#else
        public global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData MonitorCount { get; set; }
#endif
        /// <summary>Whether queue optimization is enabled for the database</summary>
        public bool? QueueOptimized { get; set; }
        /// <summary>Read requests over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Read { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Read { get; set; }
#endif
        /// <summary>99th percentile read latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? ReadLatency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> ReadLatency99 { get; set; }
#endif
        /// <summary>Average read latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? ReadLatencyMean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> ReadLatencyMean { get; set; }
#endif
        /// <summary>Throughput on database connections over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Throughput { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Throughput { get; set; }
#endif
        /// <summary>Total bandwidth used in current month (bytes)</summary>
        public int? TotalMonthlyBandwidth { get; set; }
        /// <summary>Total cost in current month</summary>
        public float? TotalMonthlyBilling { get; set; }
        /// <summary>Total read requests in current month</summary>
        public int? TotalMonthlyReadRequests { get; set; }
        /// <summary>Total requests in current month</summary>
        public int? TotalMonthlyRequests { get; set; }
        /// <summary>Total script requests in current month</summary>
        public int? TotalMonthlyScriptRequests { get; set; }
        /// <summary>Total storage used in current month (bytes)</summary>
        public int? TotalMonthlyStorage { get; set; }
        /// <summary>Total write requests in current month</summary>
        public int? TotalMonthlyWriteRequests { get; set; }
        /// <summary>Write requests over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? Write { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> Write { get; set; }
#endif
        /// <summary>99th percentile write latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? WriteLatency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> WriteLatency99 { get; set; }
#endif
        /// <summary>Average write latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? WriteLatencyMean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> WriteLatencyMean { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.DatabaseStats"/> and sets the default values.
        /// </summary>
        public DatabaseStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.DatabaseStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.DatabaseStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.DatabaseStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bandwidths", n => { Bandwidths = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "command_counts", n => { CommandCounts = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.CommandCount>(global::Soenneker.Upstash.OpenApiClient.Models.CommandCount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "connection_count", n => { ConnectionCount = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "current_storage", n => { CurrentStorage = n.GetIntValue(); } },
                { "daily_net_commands", n => { DailyNetCommands = n.GetIntValue(); } },
                { "daily_read_requests", n => { DailyReadRequests = n.GetIntValue(); } },
                { "daily_write_requests", n => { DailyWriteRequests = n.GetIntValue(); } },
                { "dailybandwidth", n => { Dailybandwidth = n.GetLongValue(); } },
                { "dailybilling", n => { Dailybilling = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dailyrequests", n => { Dailyrequests = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "days", n => { Days = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "diskusage", n => { Diskusage = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hits", n => { Hits = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "keyspace", n => { Keyspace = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "latency_99", n => { Latency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "latencymean", n => { Latencymean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "misses", n => { Misses = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "monitor_count", n => { MonitorCount = n.GetObjectValue<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue); } },
                { "queue_optimized", n => { QueueOptimized = n.GetBoolValue(); } },
                { "read", n => { Read = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "read_latency_99", n => { ReadLatency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "read_latency_mean", n => { ReadLatencyMean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "throughput", n => { Throughput = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total_monthly_bandwidth", n => { TotalMonthlyBandwidth = n.GetIntValue(); } },
                { "total_monthly_billing", n => { TotalMonthlyBilling = n.GetFloatValue(); } },
                { "total_monthly_read_requests", n => { TotalMonthlyReadRequests = n.GetIntValue(); } },
                { "total_monthly_requests", n => { TotalMonthlyRequests = n.GetIntValue(); } },
                { "total_monthly_script_requests", n => { TotalMonthlyScriptRequests = n.GetIntValue(); } },
                { "total_monthly_storage", n => { TotalMonthlyStorage = n.GetIntValue(); } },
                { "total_monthly_write_requests", n => { TotalMonthlyWriteRequests = n.GetIntValue(); } },
                { "write", n => { Write = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "write_latency_99", n => { WriteLatency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "write_latency_mean", n => { WriteLatencyMean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("bandwidths", Bandwidths);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.CommandCount>("command_counts", CommandCounts);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("connection_count", ConnectionCount);
            writer.WriteIntValue("current_storage", CurrentStorage);
            writer.WriteLongValue("dailybandwidth", Dailybandwidth);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("dailybilling", Dailybilling);
            writer.WriteIntValue("daily_net_commands", DailyNetCommands);
            writer.WriteIntValue("daily_read_requests", DailyReadRequests);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("dailyrequests", Dailyrequests);
            writer.WriteIntValue("daily_write_requests", DailyWriteRequests);
            writer.WriteCollectionOfPrimitiveValues<string>("days", Days);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("diskusage", Diskusage);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("hits", Hits);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("keyspace", Keyspace);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("latency_99", Latency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("latencymean", Latencymean);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("misses", Misses);
            writer.WriteObjectValue<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("monitor_count", MonitorCount);
            writer.WriteBoolValue("queue_optimized", QueueOptimized);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("read", Read);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("read_latency_99", ReadLatency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("read_latency_mean", ReadLatencyMean);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("throughput", Throughput);
            writer.WriteIntValue("total_monthly_bandwidth", TotalMonthlyBandwidth);
            writer.WriteFloatValue("total_monthly_billing", TotalMonthlyBilling);
            writer.WriteIntValue("total_monthly_read_requests", TotalMonthlyReadRequests);
            writer.WriteIntValue("total_monthly_requests", TotalMonthlyRequests);
            writer.WriteIntValue("total_monthly_script_requests", TotalMonthlyScriptRequests);
            writer.WriteIntValue("total_monthly_storage", TotalMonthlyStorage);
            writer.WriteIntValue("total_monthly_write_requests", TotalMonthlyWriteRequests);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("write", Write);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("write_latency_99", WriteLatency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("write_latency_mean", WriteLatencyMean);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
