// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>
    /// Security add-ons and their enablement status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatabaseSecurityAddons : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The encryptionAtRest property</summary>
        public bool? EncryptionAtRest { get; set; }
        /// <summary>The ipWhitelisting property</summary>
        public bool? IpWhitelisting { get; set; }
        /// <summary>The privateLink property</summary>
        public bool? PrivateLink { get; set; }
        /// <summary>The tlsMutualAuth property</summary>
        public bool? TlsMutualAuth { get; set; }
        /// <summary>The vpcPeering property</summary>
        public bool? VpcPeering { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons"/> and sets the default values.
        /// </summary>
        public DatabaseSecurityAddons()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.DatabaseSecurityAddons();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "encryptionAtRest", n => { EncryptionAtRest = n.GetBoolValue(); } },
                { "ipWhitelisting", n => { IpWhitelisting = n.GetBoolValue(); } },
                { "privateLink", n => { PrivateLink = n.GetBoolValue(); } },
                { "tlsMutualAuth", n => { TlsMutualAuth = n.GetBoolValue(); } },
                { "vpcPeering", n => { VpcPeering = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("encryptionAtRest", EncryptionAtRest);
            writer.WriteBoolValue("ipWhitelisting", IpWhitelisting);
            writer.WriteBoolValue("privateLink", PrivateLink);
            writer.WriteBoolValue("tlsMutualAuth", TlsMutualAuth);
            writer.WriteBoolValue("vpcPeering", VpcPeering);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
