// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Resource allocation tier</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseDbResourceSize
    {
        [EnumMember(Value = "S")]
        #pragma warning disable CS1591
        S,
        #pragma warning restore CS1591
        [EnumMember(Value = "M")]
        #pragma warning disable CS1591
        M,
        #pragma warning restore CS1591
        [EnumMember(Value = "L")]
        #pragma warning disable CS1591
        L,
        #pragma warning restore CS1591
        [EnumMember(Value = "XL")]
        #pragma warning disable CS1591
        Xl,
        #pragma warning restore CS1591
        [EnumMember(Value = "XXL")]
        #pragma warning disable CS1591
        Xxl,
        #pragma warning restore CS1591
        [EnumMember(Value = "3XL")]
        #pragma warning disable CS1591
        Value3Xl,
        #pragma warning restore CS1591
    }
}
