// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSearchIndexStatsPeriodParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "1h")]
        #pragma warning disable CS1591
        Value1H,
        #pragma warning restore CS1591
        [EnumMember(Value = "3h")]
        #pragma warning disable CS1591
        Value3H,
        #pragma warning restore CS1591
        [EnumMember(Value = "12h")]
        #pragma warning disable CS1591
        Value12H,
        #pragma warning restore CS1591
        [EnumMember(Value = "1d")]
        #pragma warning disable CS1591
        Value1D,
        #pragma warning restore CS1591
        [EnumMember(Value = "3d")]
        #pragma warning disable CS1591
        Value3D,
        #pragma warning restore CS1591
        [EnumMember(Value = "7d")]
        #pragma warning disable CS1591
        Value7D,
        #pragma warning restore CS1591
        [EnumMember(Value = "30d")]
        #pragma warning disable CS1591
        Value30D,
        #pragma warning restore CS1591
    }
}
