// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The region where database is hosted</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GlobalRegion
    {
        [EnumMember(Value = "global")]
        #pragma warning disable CS1591
        Global,
        #pragma warning restore CS1591
    }
}
