// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Account billing plan category</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QStashUserType
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "paid")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
    }
}
