// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QStashStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Daily bandwidth usage over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyBandwidths { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyBandwidths { get; set; }
#endif
        /// <summary>Bandwidth usage for the requested time periodIf 1h is specified, it shows 60 data points for every 1 minute within the last 1 hour.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyBandwidthUsed { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyBandwidthUsed { get; set; }
#endif
        /// <summary>Daily billing amounts over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyBillings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyBillings { get; set; }
#endif
        /// <summary>QStash message counts broken down by metric identifier for the requested time period.If 1h is specified, it shows 60 data points for every 1 minute within the last 1 hour.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId>? DailyQstashMessages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId> DailyQstashMessages { get; set; }
#endif
        /// <summary>Daily request metrics including workflow breakdowns</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.QStashStatsDailyRequestsItem>? DailyRequests { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.QStashStatsDailyRequestsItem> DailyRequests { get; set; }
#endif
        /// <summary>Request counts for the requested time periodIf 1h is specified, it shows 60 data points for every 1 minute within the last 1 hour.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyUsed { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyUsed { get; set; }
#endif
        /// <summary>Workflow usage metrics for the requested time periodIf 1h is specified, it shows 60 data points for every 1 minute within the last 1 hour.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyUsedWorkflow { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyUsedWorkflow { get; set; }
#endif
        /// <summary>Workflow metrics broken down by metric identifier for the requested time period.If 1h is specified, it shows 60 data points for every 1 minute within the last 1 hour.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId>? DailyWorkflowMessages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId> DailyWorkflowMessages { get; set; }
#endif
        /// <summary>Array of day names for the measurement period, typically representing all days in the current month.This includes both past and future dates within the current month, so the array covers the entire month regardless of the current day.Future days are included to align with other daily metrics arrays, allowing for consistent indexing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Days { get; set; }
#nullable restore
#else
        public List<string> Days { get; set; }
#endif
        /// <summary>Current number of messages in the dead letter queue</summary>
        public int? DlqMessageCount { get; set; }
        /// <summary>Total billing amount for the current month</summary>
        public float? TotalMonthlyBilling { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.QStashStats"/> and sets the default values.
        /// </summary>
        public QStashStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.QStashStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.QStashStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.QStashStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "daily_bandwidth_used", n => { DailyBandwidthUsed = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_bandwidths", n => { DailyBandwidths = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_billings", n => { DailyBillings = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_qstash_messages", n => { DailyQstashMessages = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_requests", n => { DailyRequests = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.QStashStatsDailyRequestsItem>(global::Soenneker.Upstash.OpenApiClient.Models.QStashStatsDailyRequestsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_used", n => { DailyUsed = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_used_workflow", n => { DailyUsedWorkflow = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_workflow_messages", n => { DailyWorkflowMessages = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId.CreateFromDiscriminatorValue)?.AsList(); } },
                { "days", n => { Days = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "dlq_message_count", n => { DlqMessageCount = n.GetIntValue(); } },
                { "total_monthly_billing", n => { TotalMonthlyBilling = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_bandwidths", DailyBandwidths);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_bandwidth_used", DailyBandwidthUsed);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_billings", DailyBillings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId>("daily_qstash_messages", DailyQstashMessages);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.QStashStatsDailyRequestsItem>("daily_requests", DailyRequests);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_used", DailyUsed);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_used_workflow", DailyUsedWorkflow);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesWithId>("daily_workflow_messages", DailyWorkflowMessages);
            writer.WriteCollectionOfPrimitiveValues<string>("days", Days);
            writer.WriteIntValue("dlq_message_count", DlqMessageCount);
            writer.WriteFloatValue("total_monthly_billing", TotalMonthlyBilling);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
