// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Region where the QStash instance is deployed</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QStashUserRegion
    {
        [EnumMember(Value = "eu-central-1")]
        #pragma warning disable CS1591
        EuCentral1,
        #pragma warning restore CS1591
        [EnumMember(Value = "us-east-1")]
        #pragma warning disable CS1591
        UsEast1,
        #pragma warning restore CS1591
    }
}
