// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QStashUser : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether the QStash account is active</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Monthly spending budget limit in dollars. 0 means no limit.</summary>
        public int? Budget { get; set; }
        /// <summary>Email of the user who created this account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Unix timestamp of account creation</summary>
        public long? CreationTime { get; set; }
        /// <summary>Customer identifier (email or team ID)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Unix timestamp of account deletion (`0` if not deleted)</summary>
        public long? DeletionTime { get; set; }
        /// <summary>Present for enterprise accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Upstash.OpenApiClient.Models.QStashUserEnterprise? Enterprise { get; set; }
#nullable restore
#else
        public global::Soenneker.Upstash.OpenApiClient.Models.QStashUserEnterprise Enterprise { get; set; }
#endif
        /// <summary>Unique identifier for the QStash user account</summary>
        public Guid? Id { get; set; }
        /// <summary>Unix timestamp of the last plan upgrade</summary>
        public long? LastPlanUpgradeTime { get; set; }
        /// <summary>Maximum bandwidth per second in bytes</summary>
        public long? MaxBandwidthPerSecond { get; set; }
        /// <summary>Maximum delay for scheduled messages in seconds</summary>
        public int? MaxDelay { get; set; }
        /// <summary>Maximum retention time for dead letter queue in milliseconds</summary>
        public long? MaxDlqRetentionTimeMilis { get; set; }
        /// <summary>Maximum dead letter queue size</summary>
        public int? MaxDlqSize { get; set; }
        /// <summary>Maximum number of endpoints allowed per topic</summary>
        public int? MaxEndpointsPerTopic { get; set; }
        /// <summary>Maximum size for events</summary>
        public int? MaxEventsSize { get; set; }
        /// <summary>Maximum global parallel processing across all endpoints</summary>
        public int? MaxGlobalParallelism { get; set; }
        /// <summary>Maximum message size in bytes</summary>
        public int? MaxMessageSize { get; set; }
        /// <summary>Maximum parallel processing per endpoint</summary>
        public int? MaxParallelism { get; set; }
        /// <summary>Maximum number of queues allowed</summary>
        public int? MaxQueues { get; set; }
        /// <summary>Soft limit for maximum requests per day</summary>
        public int? MaxRequestsPerDay { get; set; }
        /// <summary>Hard limit for maximum requests per day</summary>
        public int? MaxRequestsPerDayHard { get; set; }
        /// <summary>Maximum requests per second (rate limit)</summary>
        public int? MaxRequestsPerSecond { get; set; }
        /// <summary>Maximum number of retry attempts for failed messages</summary>
        public int? MaxRetries { get; set; }
        /// <summary>Maximum number of schedules allowed</summary>
        public int? MaxSchedules { get; set; }
        /// <summary>Maximum number of topics allowed</summary>
        public int? MaxTopics { get; set; }
        /// <summary>Transitional state while the console applies an async change (e.g. `suspended` during suspension). Omitted when no change is in progress.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModifyingState { get; set; }
#nullable restore
#else
        public string ModifyingState { get; set; }
#endif
        /// <summary>Whether production pack features are enabled</summary>
        public bool? ProdPackEnabled { get; set; }
        /// <summary>Whether Prometheus metrics export is enabled (`&quot;true&quot;` / `&quot;false&quot;` string as returned by the API)</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.QStashUserPrometheusEnabled? PrometheusEnabled { get; set; }
        /// <summary>Read-only authentication token for QStash operations</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReadOnlyToken { get; set; }
#nullable restore
#else
        public string ReadOnlyToken { get; set; }
#endif
        /// <summary>Region where the QStash instance is deployed</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.QStashUserRegion? Region { get; set; }
        /// <summary>Reserved plan price (may be `0`)</summary>
        public int? ReservedPrice { get; set; }
        /// <summary>Fixed-tier or enterprise label when applicable. May be empty/absent for non-fixed plans.Known values include `qstash_fixed_1m`, `qstash_fixed_10m`, `qstash_fixed_100m`, `qstash_fixed`.Enterprise accounts may use the prefix `enterprise:` followed by an identifier (e.g. `enterprise:acme`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReservedType { get; set; }
#nullable restore
#else
        public string ReservedType { get; set; }
#endif
        /// <summary>Current state of the QStash account (e.g. `active`, `passive`; other values may be returned)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Request timeout in seconds</summary>
        public int? Timeout { get; set; }
        /// <summary>Authentication token for QStash operations</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>Account billing plan category</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.QStashUserType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.QStashUser"/> and sets the default values.
        /// </summary>
        public QStashUser()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.QStashUser"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.QStashUser CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.QStashUser();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "budget", n => { Budget = n.GetIntValue(); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "creation_time", n => { CreationTime = n.GetLongValue(); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "deletion_time", n => { DeletionTime = n.GetLongValue(); } },
                { "enterprise", n => { Enterprise = n.GetObjectValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserEnterprise>(global::Soenneker.Upstash.OpenApiClient.Models.QStashUserEnterprise.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "last_plan_upgrade_time", n => { LastPlanUpgradeTime = n.GetLongValue(); } },
                { "max_bandwidth_per_second", n => { MaxBandwidthPerSecond = n.GetLongValue(); } },
                { "max_delay", n => { MaxDelay = n.GetIntValue(); } },
                { "max_dlq_retention_time_milis", n => { MaxDlqRetentionTimeMilis = n.GetLongValue(); } },
                { "max_dlq_size", n => { MaxDlqSize = n.GetIntValue(); } },
                { "max_endpoints_per_topic", n => { MaxEndpointsPerTopic = n.GetIntValue(); } },
                { "max_events_size", n => { MaxEventsSize = n.GetIntValue(); } },
                { "max_global_parallelism", n => { MaxGlobalParallelism = n.GetIntValue(); } },
                { "max_message_size", n => { MaxMessageSize = n.GetIntValue(); } },
                { "max_parallelism", n => { MaxParallelism = n.GetIntValue(); } },
                { "max_queues", n => { MaxQueues = n.GetIntValue(); } },
                { "max_requests_per_day", n => { MaxRequestsPerDay = n.GetIntValue(); } },
                { "max_requests_per_day_hard", n => { MaxRequestsPerDayHard = n.GetIntValue(); } },
                { "max_requests_per_second", n => { MaxRequestsPerSecond = n.GetIntValue(); } },
                { "max_retries", n => { MaxRetries = n.GetIntValue(); } },
                { "max_schedules", n => { MaxSchedules = n.GetIntValue(); } },
                { "max_topics", n => { MaxTopics = n.GetIntValue(); } },
                { "modifying_state", n => { ModifyingState = n.GetStringValue(); } },
                { "prod_pack_enabled", n => { ProdPackEnabled = n.GetBoolValue(); } },
                { "prometheus_enabled", n => { PrometheusEnabled = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserPrometheusEnabled>(); } },
                { "read_only_token", n => { ReadOnlyToken = n.GetStringValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserRegion>(); } },
                { "reserved_price", n => { ReservedPrice = n.GetIntValue(); } },
                { "reserved_type", n => { ReservedType = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteIntValue("budget", Budget);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteLongValue("creation_time", CreationTime);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteLongValue("deletion_time", DeletionTime);
            writer.WriteObjectValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserEnterprise>("enterprise", Enterprise);
            writer.WriteGuidValue("id", Id);
            writer.WriteLongValue("last_plan_upgrade_time", LastPlanUpgradeTime);
            writer.WriteLongValue("max_bandwidth_per_second", MaxBandwidthPerSecond);
            writer.WriteIntValue("max_delay", MaxDelay);
            writer.WriteLongValue("max_dlq_retention_time_milis", MaxDlqRetentionTimeMilis);
            writer.WriteIntValue("max_dlq_size", MaxDlqSize);
            writer.WriteIntValue("max_endpoints_per_topic", MaxEndpointsPerTopic);
            writer.WriteIntValue("max_events_size", MaxEventsSize);
            writer.WriteIntValue("max_global_parallelism", MaxGlobalParallelism);
            writer.WriteIntValue("max_message_size", MaxMessageSize);
            writer.WriteIntValue("max_parallelism", MaxParallelism);
            writer.WriteIntValue("max_queues", MaxQueues);
            writer.WriteIntValue("max_requests_per_day", MaxRequestsPerDay);
            writer.WriteIntValue("max_requests_per_day_hard", MaxRequestsPerDayHard);
            writer.WriteIntValue("max_requests_per_second", MaxRequestsPerSecond);
            writer.WriteIntValue("max_retries", MaxRetries);
            writer.WriteIntValue("max_schedules", MaxSchedules);
            writer.WriteIntValue("max_topics", MaxTopics);
            writer.WriteStringValue("modifying_state", ModifyingState);
            writer.WriteBoolValue("prod_pack_enabled", ProdPackEnabled);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserPrometheusEnabled>("prometheus_enabled", PrometheusEnabled);
            writer.WriteStringValue("read_only_token", ReadOnlyToken);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserRegion>("region", Region);
            writer.WriteIntValue("reserved_price", ReservedPrice);
            writer.WriteStringValue("reserved_type", ReservedType);
            writer.WriteStringValue("state", State);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteStringValue("token", Token);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.QStashUserType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
