// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchIndex : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unix timestamp of creation</summary>
        public long? CreationTime { get; set; }
        /// <summary>The associated ID of the owner of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>The REST endpoint of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>Unique ID of the index</summary>
        public Guid? Id { get; set; }
        /// <summary>Whether input enrichment is enabled for this index</summary>
        public bool? InputEnrichmentEnabled { get; set; }
        /// <summary>Maximum daily query operations (-1 for unlimited)</summary>
        public int? MaxDailyQueries { get; set; }
        /// <summary>Maximum daily update operations (-1 for unlimited)</summary>
        public int? MaxDailyUpdates { get; set; }
        /// <summary>Maximum monthly bandwidth in bytes (-1 for unlimited)</summary>
        public int? MaxMonthlyBandwidth { get; set; }
        /// <summary>Maximum monthly rerank operations (-1 for unlimited)</summary>
        public int? MaxMonthlyReranks { get; set; }
        /// <summary>Maximum query operations per second (rate limit)</summary>
        public int? MaxQueryPerSecond { get; set; }
        /// <summary>Maximum number of reads allowed per request</summary>
        public int? MaxReadsPerRequest { get; set; }
        /// <summary>Maximum number of vectors allowed in the index</summary>
        public int? MaxVectorCount { get; set; }
        /// <summary>Maximum number of writes allowed per request</summary>
        public int? MaxWritesPerRequest { get; set; }
        /// <summary>Maximum write operations per second (rate limit)</summary>
        public int? MaxWritesPerSecond { get; set; }
        /// <summary>Name of the search index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The REST authentication read only token for the search index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReadOnlyToken { get; set; }
#nullable restore
#else
        public string ReadOnlyToken { get; set; }
#endif
        /// <summary>The region where the index is currently deployed</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.SearchIndexRegion? Region { get; set; }
        /// <summary>Throughput metrics over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? ThroughputVector { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> ThroughputVector { get; set; }
#endif
        /// <summary>The REST authentication token for the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>The payment plan of the index</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.SearchIndexType? Type { get; set; }
        /// <summary>The email associated with Vercel integration, if any. Empty string otherwise.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VercelEmail { get; set; }
#nullable restore
#else
        public string VercelEmail { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.SearchIndex"/> and sets the default values.
        /// </summary>
        public SearchIndex()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.SearchIndex"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.SearchIndex CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.SearchIndex();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creation_time", n => { CreationTime = n.GetLongValue(); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "input_enrichment_enabled", n => { InputEnrichmentEnabled = n.GetBoolValue(); } },
                { "max_daily_queries", n => { MaxDailyQueries = n.GetIntValue(); } },
                { "max_daily_updates", n => { MaxDailyUpdates = n.GetIntValue(); } },
                { "max_monthly_bandwidth", n => { MaxMonthlyBandwidth = n.GetIntValue(); } },
                { "max_monthly_reranks", n => { MaxMonthlyReranks = n.GetIntValue(); } },
                { "max_query_per_second", n => { MaxQueryPerSecond = n.GetIntValue(); } },
                { "max_reads_per_request", n => { MaxReadsPerRequest = n.GetIntValue(); } },
                { "max_vector_count", n => { MaxVectorCount = n.GetIntValue(); } },
                { "max_writes_per_request", n => { MaxWritesPerRequest = n.GetIntValue(); } },
                { "max_writes_per_second", n => { MaxWritesPerSecond = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "read_only_token", n => { ReadOnlyToken = n.GetStringValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.SearchIndexRegion>(); } },
                { "throughput_vector", n => { ThroughputVector = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.SearchIndexType>(); } },
                { "vercel_email", n => { VercelEmail = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("creation_time", CreationTime);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("input_enrichment_enabled", InputEnrichmentEnabled);
            writer.WriteIntValue("max_daily_queries", MaxDailyQueries);
            writer.WriteIntValue("max_daily_updates", MaxDailyUpdates);
            writer.WriteIntValue("max_monthly_bandwidth", MaxMonthlyBandwidth);
            writer.WriteIntValue("max_monthly_reranks", MaxMonthlyReranks);
            writer.WriteIntValue("max_query_per_second", MaxQueryPerSecond);
            writer.WriteIntValue("max_reads_per_request", MaxReadsPerRequest);
            writer.WriteIntValue("max_vector_count", MaxVectorCount);
            writer.WriteIntValue("max_writes_per_request", MaxWritesPerRequest);
            writer.WriteIntValue("max_writes_per_second", MaxWritesPerSecond);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("read_only_token", ReadOnlyToken);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.SearchIndexRegion>("region", Region);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("throughput_vector", ThroughputVector);
            writer.WriteStringValue("token", Token);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.SearchIndexType>("type", Type);
            writer.WriteStringValue("vercel_email", VercelEmail);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
