// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The new plan for the index</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SetIndexPlanRequestTargetPlan
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "payg")]
        #pragma warning disable CS1591
        Payg,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed")]
        #pragma warning disable CS1591
        FixedValue,
        #pragma warning restore CS1591
    }
}
