// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Target plan to upgrade to</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SetQStashPlanRequestPlanName
    {
        [EnumMember(Value = "paid")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
        [EnumMember(Value = "qstash_fixed_1m")]
        #pragma warning disable CS1591
        QstashFixed1M,
        #pragma warning restore CS1591
        [EnumMember(Value = "qstash_fixed_10m")]
        #pragma warning disable CS1591
        QstashFixed10M,
        #pragma warning restore CS1591
        [EnumMember(Value = "qstash_fixed_100m")]
        #pragma warning disable CS1591
        QstashFixed100M,
        #pragma warning restore CS1591
    }
}
