// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Role of the team member</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamMemberMemberRole
    {
        [EnumMember(Value = "owner")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "dev")]
        #pragma warning disable CS1591
        Dev,
        #pragma warning restore CS1591
        [EnumMember(Value = "finance")]
        #pragma warning disable CS1591
        Finance,
        #pragma warning restore CS1591
    }
}
