// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The sparse embedding model to be used for indexes</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VectorIndexSparseEmbeddingModel
    {
        [EnumMember(Value = "BM25")]
        #pragma warning disable CS1591
        Bm25,
        #pragma warning restore CS1591
        [EnumMember(Value = "BGE_M3")]
        #pragma warning disable CS1591
        BgeM3,
        #pragma warning restore CS1591
    }
}
