// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The region where the index is currently deployed</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VectorIndexRegion
    {
        [EnumMember(Value = "eu-west-1")]
        #pragma warning disable CS1591
        EuWest1,
        #pragma warning restore CS1591
        [EnumMember(Value = "us-east-1")]
        #pragma warning disable CS1591
        UsEast1,
        #pragma warning restore CS1591
        [EnumMember(Value = "us-central1")]
        #pragma warning disable CS1591
        UsCentral1,
        #pragma warning restore CS1591
    }
}
