// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VectorIndex : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation time of the vector index in UTC as unix timestamp.</summary>
        public double? CreationTime { get; set; }
        /// <summary>The associated ID of the owner of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>The amount of values in a single vector</summary>
        public double? DimensionCount { get; set; }
        /// <summary>The predefined embedding model to vectorize your plain text</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexEmbeddingModel? EmbeddingModel { get; set; }
        /// <summary>The REST endpoint of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>Unique ID of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The type of the vector index</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexIndexType? IndexType { get; set; }
        /// <summary>The number of maximum query operations you can perform in a day. Only query operations are included in query count.</summary>
        public double? MaxDailyQueries { get; set; }
        /// <summary>The number of maximum update operations you can perform in a day. Only upsert operations are included in update count.</summary>
        public double? MaxDailyUpdates { get; set; }
        /// <summary>The maximum amount of monthly bandwidth for the index. Unit is bytes. -1 if the limit is unlimited.</summary>
        public double? MaxMonthlyBandwidth { get; set; }
        /// <summary>The number of maximum query operations you can perform per second. Only query operations are included in query count.</summary>
        public double? MaxQueryPerSecond { get; set; }
        /// <summary>The number of maximum vectors in a read operation. Query and fetch operations are included in read operations.</summary>
        public double? MaxReadsPerRequest { get; set; }
        /// <summary>The amount of maximum size for the total metadata sizes in your index.</summary>
        public double? MaxTotalMetadataSize { get; set; }
        /// <summary>The number of maximum that your index can contain</summary>
        public double? MaxVectorCount { get; set; }
        /// <summary>The number of maximum vectors in a write operation. Only upsert operations are included in write operations.</summary>
        public double? MaxWritesPerRequest { get; set; }
        /// <summary>The number of maximum write operations you can perform per second. Only upsert operations are included in write count.</summary>
        public double? MaxWritesPerSecond { get; set; }
        /// <summary>The name of the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The REST authentication read only token for the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReadOnlyToken { get; set; }
#nullable restore
#else
        public string ReadOnlyToken { get; set; }
#endif
        /// <summary>The region where the index is currently deployed</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexRegion? Region { get; set; }
        /// <summary>Monthly pricing of your index. Only available for fixed and pro plans.</summary>
        public double? ReservedPrice { get; set; }
        /// <summary>Similarity function that&apos;s used to calculate the distance between two vectors</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexSimilarityFunction? SimilarityFunction { get; set; }
        /// <summary>The sparse embedding model to be used for indexes</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexSparseEmbeddingModel? SparseEmbeddingModel { get; set; }
        /// <summary>Throughput data for the vector index over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? ThroughputVector { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> ThroughputVector { get; set; }
#endif
        /// <summary>The REST authentication token for the index</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>The payment plan of the index</summary>
        public global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex"/> and sets the default values.
        /// </summary>
        public VectorIndex()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creation_time", n => { CreationTime = n.GetDoubleValue(); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "dimension_count", n => { DimensionCount = n.GetDoubleValue(); } },
                { "embedding_model", n => { EmbeddingModel = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexEmbeddingModel>(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "index_type", n => { IndexType = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexIndexType>(); } },
                { "max_daily_queries", n => { MaxDailyQueries = n.GetDoubleValue(); } },
                { "max_daily_updates", n => { MaxDailyUpdates = n.GetDoubleValue(); } },
                { "max_monthly_bandwidth", n => { MaxMonthlyBandwidth = n.GetDoubleValue(); } },
                { "max_query_per_second", n => { MaxQueryPerSecond = n.GetDoubleValue(); } },
                { "max_reads_per_request", n => { MaxReadsPerRequest = n.GetDoubleValue(); } },
                { "max_total_metadata_size", n => { MaxTotalMetadataSize = n.GetDoubleValue(); } },
                { "max_vector_count", n => { MaxVectorCount = n.GetDoubleValue(); } },
                { "max_writes_per_request", n => { MaxWritesPerRequest = n.GetDoubleValue(); } },
                { "max_writes_per_second", n => { MaxWritesPerSecond = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "read_only_token", n => { ReadOnlyToken = n.GetStringValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexRegion>(); } },
                { "reserved_price", n => { ReservedPrice = n.GetDoubleValue(); } },
                { "similarity_function", n => { SimilarityFunction = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexSimilarityFunction>(); } },
                { "sparse_embedding_model", n => { SparseEmbeddingModel = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexSparseEmbeddingModel>(); } },
                { "throughput_vector", n => { ThroughputVector = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("creation_time", CreationTime);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteDoubleValue("dimension_count", DimensionCount);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexEmbeddingModel>("embedding_model", EmbeddingModel);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexIndexType>("index_type", IndexType);
            writer.WriteDoubleValue("max_daily_queries", MaxDailyQueries);
            writer.WriteDoubleValue("max_daily_updates", MaxDailyUpdates);
            writer.WriteDoubleValue("max_monthly_bandwidth", MaxMonthlyBandwidth);
            writer.WriteDoubleValue("max_query_per_second", MaxQueryPerSecond);
            writer.WriteDoubleValue("max_reads_per_request", MaxReadsPerRequest);
            writer.WriteDoubleValue("max_total_metadata_size", MaxTotalMetadataSize);
            writer.WriteDoubleValue("max_vector_count", MaxVectorCount);
            writer.WriteDoubleValue("max_writes_per_request", MaxWritesPerRequest);
            writer.WriteDoubleValue("max_writes_per_second", MaxWritesPerSecond);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("read_only_token", ReadOnlyToken);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexRegion>("region", Region);
            writer.WriteDoubleValue("reserved_price", ReservedPrice);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexSimilarityFunction>("similarity_function", SimilarityFunction);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexSparseEmbeddingModel>("sparse_embedding_model", SparseEmbeddingModel);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("throughput_vector", ThroughputVector);
            writer.WriteStringValue("token", Token);
            writer.WriteEnumValue<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndexType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
