// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>The predefined embedding model to vectorize your plain text</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VectorIndexEmbeddingModel
    {
        [EnumMember(Value = "BGE_SMALL_EN_V1_5")]
        #pragma warning disable CS1591
        BgeSmallEnV15,
        #pragma warning restore CS1591
        [EnumMember(Value = "BGE_BASE_EN_V1_5")]
        #pragma warning disable CS1591
        BgeBaseEnV15,
        #pragma warning restore CS1591
        [EnumMember(Value = "BGE_LARGE_EN_V1_5")]
        #pragma warning disable CS1591
        BgeLargeEnV15,
        #pragma warning restore CS1591
        [EnumMember(Value = "BGE_M3")]
        #pragma warning disable CS1591
        BgeM3,
        #pragma warning restore CS1591
    }
}
