// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    /// <summary>Similarity function that&apos;s used to calculate the distance between two vectors</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VectorIndexSimilarityFunction
    {
        [EnumMember(Value = "COSINE")]
        #pragma warning disable CS1591
        Cosine,
        #pragma warning restore CS1591
        [EnumMember(Value = "EUCLIDEAN")]
        #pragma warning disable CS1591
        Euclidean,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOT_PRODUCT")]
        #pragma warning disable CS1591
        DotProduct,
        #pragma warning restore CS1591
    }
}
