// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Upstash.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VectorStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current number of vectors in the index</summary>
        public int? CurrentVectorCount { get; set; }
        /// <summary>Daily bandwidth usage over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyBandwidths { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyBandwidths { get; set; }
#endif
        /// <summary>Total number of query operations executed today</summary>
        public int? DailyQueryCount { get; set; }
        /// <summary>Daily query requests over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyQueryRequests { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyQueryRequests { get; set; }
#endif
        /// <summary>Total number of rerank operations executed today</summary>
        public int? DailyRerankCount { get; set; }
        /// <summary>Daily rerank requests over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyRerankRequests { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyRerankRequests { get; set; }
#endif
        /// <summary>Total number of update operations executed today</summary>
        public int? DailyUpdateCount { get; set; }
        /// <summary>Daily update requests over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DailyUpdateRequests { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DailyUpdateRequests { get; set; }
#endif
        /// <summary>Data size over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? DataSize { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> DataSize { get; set; }
#endif
        /// <summary>Days of the week for measurement</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Days { get; set; }
#nullable restore
#else
        public List<string> Days { get; set; }
#endif
        /// <summary>99th percentile embedding latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? EmbedsLatency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> EmbedsLatency99 { get; set; }
#endif
        /// <summary>Average embedding latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? EmbedsLatencyMean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> EmbedsLatencyMean { get; set; }
#endif
        /// <summary>Total bandwidth used in current month (bytes)</summary>
        public int? MonthlyBandwidthUsage { get; set; }
        /// <summary>Total cost in current month</summary>
        public float? MonthlyCost { get; set; }
        /// <summary>Total query operations in current month</summary>
        public int? MonthlyQueryCount { get; set; }
        /// <summary>Total rerank operations in current month</summary>
        public int? MonthlyRerankCount { get; set; }
        /// <summary>Total update operations in current month</summary>
        public int? MonthlyUpdateCount { get; set; }
        /// <summary>Number of pending index operations</summary>
        public int? PendingIndexCount { get; set; }
        /// <summary>99th percentile query latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? QueryLatency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> QueryLatency99 { get; set; }
#endif
        /// <summary>Average query latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? QueryLatencyMean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> QueryLatencyMean { get; set; }
#endif
        /// <summary>Query throughput over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? QueryThroughput { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> QueryThroughput { get; set; }
#endif
        /// <summary>99th percentile rerank latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? RerankLatency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> RerankLatency99 { get; set; }
#endif
        /// <summary>Average rerank latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? RerankLatencyMean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> RerankLatencyMean { get; set; }
#endif
        /// <summary>Current storage used (bytes)</summary>
        public int? StorageUsage { get; set; }
        /// <summary>99th percentile update latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? UpdateLatency99 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> UpdateLatency99 { get; set; }
#endif
        /// <summary>Average update latency over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? UpdateLatencyMean { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> UpdateLatencyMean { get; set; }
#endif
        /// <summary>Update throughput over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? UpdateThroughput { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> UpdateThroughput { get; set; }
#endif
        /// <summary>Vector count over time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>? VectorCount { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData> VectorCount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Models.VectorStats"/> and sets the default values.
        /// </summary>
        public VectorStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.VectorStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Upstash.OpenApiClient.Models.VectorStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Upstash.OpenApiClient.Models.VectorStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_vector_count", n => { CurrentVectorCount = n.GetIntValue(); } },
                { "daily_bandwidths", n => { DailyBandwidths = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_query_count", n => { DailyQueryCount = n.GetIntValue(); } },
                { "daily_query_requests", n => { DailyQueryRequests = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_rerank_count", n => { DailyRerankCount = n.GetIntValue(); } },
                { "daily_rerank_requests", n => { DailyRerankRequests = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily_update_count", n => { DailyUpdateCount = n.GetIntValue(); } },
                { "daily_update_requests", n => { DailyUpdateRequests = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "data_size", n => { DataSize = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "days", n => { Days = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "embeds_latency_99", n => { EmbedsLatency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "embeds_latency_mean", n => { EmbedsLatencyMean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "monthly_bandwidth_usage", n => { MonthlyBandwidthUsage = n.GetIntValue(); } },
                { "monthly_cost", n => { MonthlyCost = n.GetFloatValue(); } },
                { "monthly_query_count", n => { MonthlyQueryCount = n.GetIntValue(); } },
                { "monthly_rerank_count", n => { MonthlyRerankCount = n.GetIntValue(); } },
                { "monthly_update_count", n => { MonthlyUpdateCount = n.GetIntValue(); } },
                { "pending_index_count", n => { PendingIndexCount = n.GetIntValue(); } },
                { "query_latency_99", n => { QueryLatency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "query_latency_mean", n => { QueryLatencyMean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "query_throughput", n => { QueryThroughput = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rerank_latency_99", n => { RerankLatency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rerank_latency_mean", n => { RerankLatencyMean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "storage_usage", n => { StorageUsage = n.GetIntValue(); } },
                { "update_latency_99", n => { UpdateLatency99 = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "update_latency_mean", n => { UpdateLatencyMean = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "update_throughput", n => { UpdateThroughput = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "vector_count", n => { VectorCount = n.GetCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>(global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("current_vector_count", CurrentVectorCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_bandwidths", DailyBandwidths);
            writer.WriteIntValue("daily_query_count", DailyQueryCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_query_requests", DailyQueryRequests);
            writer.WriteIntValue("daily_rerank_count", DailyRerankCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_rerank_requests", DailyRerankRequests);
            writer.WriteIntValue("daily_update_count", DailyUpdateCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("daily_update_requests", DailyUpdateRequests);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("data_size", DataSize);
            writer.WriteCollectionOfPrimitiveValues<string>("days", Days);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("embeds_latency_99", EmbedsLatency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("embeds_latency_mean", EmbedsLatencyMean);
            writer.WriteIntValue("monthly_bandwidth_usage", MonthlyBandwidthUsage);
            writer.WriteFloatValue("monthly_cost", MonthlyCost);
            writer.WriteIntValue("monthly_query_count", MonthlyQueryCount);
            writer.WriteIntValue("monthly_rerank_count", MonthlyRerankCount);
            writer.WriteIntValue("monthly_update_count", MonthlyUpdateCount);
            writer.WriteIntValue("pending_index_count", PendingIndexCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("query_latency_99", QueryLatency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("query_latency_mean", QueryLatencyMean);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("query_throughput", QueryThroughput);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("rerank_latency_99", RerankLatency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("rerank_latency_mean", RerankLatencyMean);
            writer.WriteIntValue("storage_usage", StorageUsage);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("update_latency_99", UpdateLatency99);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("update_latency_mean", UpdateLatencyMean);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("update_throughput", UpdateThroughput);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Upstash.OpenApiClient.Models.TimeSeriesData>("vector_count", VectorCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
