// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Upstash.OpenApiClient.Redis.CreateBackup;
using Soenneker.Upstash.OpenApiClient.Redis.Database;
using Soenneker.Upstash.OpenApiClient.Redis.Databases;
using Soenneker.Upstash.OpenApiClient.Redis.DeleteBackup;
using Soenneker.Upstash.OpenApiClient.Redis.DisableAutoupgrade;
using Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup;
using Soenneker.Upstash.OpenApiClient.Redis.DisableEviction;
using Soenneker.Upstash.OpenApiClient.Redis.EnableAutoupgrade;
using Soenneker.Upstash.OpenApiClient.Redis.EnableDailybackup;
using Soenneker.Upstash.OpenApiClient.Redis.EnableEviction;
using Soenneker.Upstash.OpenApiClient.Redis.EnableTls;
using Soenneker.Upstash.OpenApiClient.Redis.Item;
using Soenneker.Upstash.OpenApiClient.Redis.ListBackup;
using Soenneker.Upstash.OpenApiClient.Redis.MoveToTeam;
using Soenneker.Upstash.OpenApiClient.Redis.Rename;
using Soenneker.Upstash.OpenApiClient.Redis.ResetPassword;
using Soenneker.Upstash.OpenApiClient.Redis.RestoreBackup;
using Soenneker.Upstash.OpenApiClient.Redis.Stats;
using Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget;
using Soenneker.Upstash.OpenApiClient.Redis.UpdateRegions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Upstash.OpenApiClient.Redis
{
    /// <summary>
    /// Builds and executes requests for operations under \redis
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RedisRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The createBackup property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.CreateBackup.CreateBackupRequestBuilder CreateBackup
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.CreateBackup.CreateBackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The database property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.Database.DatabaseRequestBuilder Database
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The databases property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.Databases.DatabasesRequestBuilder Databases
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.Databases.DatabasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deleteBackup property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.DeleteBackup.DeleteBackupRequestBuilder DeleteBackup
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.DeleteBackup.DeleteBackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disableAutoupgrade property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.DisableAutoupgrade.DisableAutoupgradeRequestBuilder DisableAutoupgrade
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.DisableAutoupgrade.DisableAutoupgradeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disableDailybackup property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.DisableDailybackupRequestBuilder DisableDailybackup
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.DisableDailybackup.DisableDailybackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disableEviction property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.DisableEviction.DisableEvictionRequestBuilder DisableEviction
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.DisableEviction.DisableEvictionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enableAutoupgrade property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.EnableAutoupgrade.EnableAutoupgradeRequestBuilder EnableAutoupgrade
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.EnableAutoupgrade.EnableAutoupgradeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enableDailybackup property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.EnableDailybackup.EnableDailybackupRequestBuilder EnableDailybackup
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.EnableDailybackup.EnableDailybackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enableEviction property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.EnableEviction.EnableEvictionRequestBuilder EnableEviction
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.EnableEviction.EnableEvictionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enableTls property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.EnableTls.EnableTlsRequestBuilder EnableTls
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.EnableTls.EnableTlsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listBackup property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.ListBackup.ListBackupRequestBuilder ListBackup
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.ListBackup.ListBackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The moveToTeam property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.MoveToTeam.MoveToTeamRequestBuilder MoveToTeam
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.MoveToTeam.MoveToTeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rename property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.Rename.RenameRequestBuilder Rename
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.Rename.RenameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restoreBackup property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.RestoreBackup.RestoreBackupRequestBuilder RestoreBackup
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.RestoreBackup.RestoreBackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.Stats.StatsRequestBuilder Stats
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateBudget property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.UpdateBudgetRequestBuilder UpdateBudget
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.UpdateBudget.UpdateBudgetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateRegions property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Redis.UpdateRegions.UpdateRegionsRequestBuilder UpdateRegions
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Redis.UpdateRegions.UpdateRegionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Upstash.OpenApiClient.redis.item collection</summary>
        /// <param name="position">The ID of the database whose plan will be changed</param>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.Item.RedisItemRequestBuilder"/></returns>
        public global::Soenneker.Upstash.OpenApiClient.Redis.Item.RedisItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Upstash.OpenApiClient.Redis.Item.RedisItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.RedisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RedisRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/redis", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Redis.RedisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RedisRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/redis", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
