// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Upstash.OpenApiClient.Models;
using Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Item;
using Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Stats;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \vector\index
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IndexRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The stats property</summary>
        public global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Stats.StatsRequestBuilder Stats
        {
            get => new global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Upstash.OpenApiClient.vector.index.item collection</summary>
        /// <param name="position">The unique ID of the index to fetch</param>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Item.IndexItemRequestBuilder"/></returns>
        public global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Item.IndexItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.Item.IndexItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.IndexRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IndexRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/vector/index", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.IndexRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IndexRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/vector/index", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint returns the data related to all indices of an account as a list.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex>(requestInfo, global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// This endpoint creates an index.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex?> PostAsync(global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex> PostAsync(global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex>(requestInfo, global::Soenneker.Upstash.OpenApiClient.Models.VectorIndex.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint returns the data related to all indices of an account as a list.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This endpoint creates an index.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Upstash.OpenApiClient.Models.CreateIndexRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.IndexRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.IndexRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Upstash.OpenApiClient.Vector.IndexNamespace.IndexRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
